Traceback (most recent call last):
  File "rrt_sac_demo.py", line 341, in <module>
    ped_sim = Demo()
  File "rrt_sac_demo.py", line 84, in __init__
    exp_obs_dim_, exp_act_dim_ = self.ped_sim_.get_dim()
  File "/home/brain5/catkin_ws/src/social_navigation/scripts/gazebo_master_rrt.py", line 458, in get_dim
    o = self.reset()
  File "/home/brain5/catkin_ws/src/social_navigation/scripts/gazebo_master_rrt.py", line 348, in reset
    self.update_state()
  File "/home/brain5/catkin_ws/src/social_navigation/scripts/gazebo_master_rrt.py", line 556, in update_state
    gx, gy = transform_coordinate(self.local_goal_.x - jx, self.local_goal_.y - jy, ct, st)
AttributeError: 'PedSim' object has no attribute 'local_goal_'
[31m[ERROR] [1651558703.170281, 322.199000]: bad callback: <bound method Demo.callback of <__main__.Demo object at 0x7f06766c1d30>>
[31mTraceback (most recent call last):
[31m  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
[31m    cb(msg)
[31m  File "rrt_sac_demo.py", line 123, in callback
[31m    if len(self.path) > self.lookahead_:
[31mAttributeError: 'Demo' object has no attribute 'lookahead_'