/home/brain5/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py:80: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:112.)
  return torch._C._cuda_getDeviceCount() > 0
{'exp_name': 'pedsim_cpo', 'exp_epi_len': 200, 'pi_hidden_layers': [128, 128], 'pi_options': ['default', 'leaky-relu', 'default'], 'replay_size': 10000, 'gamma': 0.99, 'lambda': 0.97, 'polyak': 0.995, 'alpha': 0.002, 'learning_rate': 0.0001, 'epochs': 1000, 'steps_per_epoch': 1000, 'batch_size': 256, 'n_log_epi': 10, 'start_steps': 1000, 'update_after': 1000, 'update_every': 200, 'save_interval': 10, 'plot_rendering': True, 'seed': 1}
model_state:
  model_name: "goal"
  pose:
    position:
      x: 27.330440000000003
      y: -0.25669999999999504
      z: 3.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  reference_frame: ''
success: True
status_message: "SetModelState: set model state done"
model_state:
  model_name: "goal"
  pose:
    position:
      x: 14.361640000000016
      y: -0.5587400000000002
      z: 3.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  reference_frame: ''
success: True
status_message: "SetModelState: set model state done"
Traceback (most recent call last):
  File "cpo_discrete.py", line 423, in <module>
    o2, r, d, info = env_.step(a)
  File "/home/brain5/catkin_ws/src/social_navigation/scripts/gazebo_master.py", line 369, in step
    collision_cost = self.map_cost_coeff_ * collision_cost(min(min(self.lidar_state_),oob_dist))
UnboundLocalError: local variable 'collision_cost' referenced before assignment